image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  github_oauth_token:
    secure: H1vW5fnfAOt5/c5f1qnaatUjFVAPc2oZnxDBFutJZL58LxAyJNRLtfIBrcHnSg8y
  
# Patch .NET Core csproj files to set version information
#
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  # assembly_version: '{version}'
  # file_version: '{version}'
  # informational_version: '{version}'


# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
init:
# nothing here

install:
- choco install gitversion.portable -pre -y
- choco install opencover.portable
- choco install codecov
# Run gitversion before appveyor will patch the csproj files with version info.
# Note that the full patch is specified. Otherwise the default (older) gitversion will be used.
- C:\ProgramData\chocolatey\lib/gitversion.portable/tools/gitversion.exe /l console /output buildserver

before_build:
- dotnet restore src\ImageHash.sln

build_script:
- msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" src\ImageHash.sln 

# after_build:

# before_test:

test_script:
- .scripts\TestCoverage.bat

after_test:
- ps: .scripts\pack.ps1
- codecov -f coverage-dotnet.xml

# build_success:

# on_finish:

artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages

deploy:
  - provider: NuGet
    name: pre-release
    server: https://www.myget.org/F/coenm/api/v2/package
    api_key:
        secure: t8JtzPkpHidqOii+bLuSiOKgqzsdoSCBI3Sc/Uy6D9jWfxNd7zUUhhTgGHj5rpV9
    skip_symbols: true
    # symbol_server: https://www.myget.org/F/coenm/symbols/api/v2/package
    artifact: /.*\.nupkg/
