image: Visual Studio 2017
configuration: Release
#platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  github_oauth_token:
    secure: H1vW5fnfAOt5/c5f1qnaatUjFVAPc2oZnxDBFutJZL58LxAyJNRLtfIBrcHnSg8y
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%GitVersion_NuGetVersion%'
  package_version: '%GitVersion_NuGetVersion%'
  # assembly_version: '{version}'
  # file_version: '{version}'
  # informational_version: '{version}'

install:
- cmd: >-
    choco install gitversion.portable -pre -y

    choco install opencover.portable -y

    choco install codecov -y
    
    C:\ProgramData\chocolatey\lib/gitversion.portable/tools/gitversion.exe /l console /output buildserver

    git submodule update --init --recursive


before_build:
- dotnet restore src\ImageHash.sln

build_script:
- dotnet build src\ImageHash.sln
#- msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" src\ImageHash.sln 

test_script:
- ps: .scripts\TestCoverage.ps1

after_test:
- ps: .scripts\pack.ps1
- codecov -f coverage-dotnet.xml


artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages

deploy:
  - provider: NuGet
    name: pre-release
    server: https://www.myget.org/F/coenm/api/v2/package
    api_key:
        secure: t8JtzPkpHidqOii+bLuSiOKgqzsdoSCBI3Sc/Uy6D9jWfxNd7zUUhhTgGHj5rpV9
    skip_symbols: true
    # symbol_server: https://www.myget.org/F/coenm/symbols/api/v2/package
    artifact: /.*\.nupkg/
    on:
        branch: /(master|release.*|develop)/	
